### ISSUE TITLE
Doesn't build in Xcode 8.2.1 due to Swift 2.3 syntax - please upgrade to Swift 3 syntax

### ISSUE THREAD

**Issue by iosdev-republicofapps** [3lvis/Hex#8]
This Form pod is awesome, and I'm eager to use it! Thanks so much for sharing it. :-)

I'm trying to build in Xcode 8.2.1 (8C1002) on OS X 10.12.3. My app has an iOS 10 target and is pure Objective-C.

I'm actually using Hex only by virtue of it's being a dependency of the Form pod, I'm not using Hex directly.  See the related Form issue: https://github.com/hyperoslo/Form/issues/565

When I add the Form pod, Xcode asks if it can convert the Hex pod from Swift 2.3 to Swift 3. I tell it no, because I don't want to convert a Pod dependency since I should treat local pods as readonly. Then Xcode warns me that due to Hex's outdated Swift syntax, it won't be able to build properly and that certain "editor features" may not work right ...

I tried to build but got the error:

`Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

Any way we could upgrade Hex to Swift 3 syntax so that I can build?  :-)  I'm happy to help.

Thanks.

**Comment by iosdev-republicofapps** [comment]
Fixed by adding the following to the end of my Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

Feels gross, but it works!  :-)

**Comment by 3lvis** [comment]
Hex should be in the latest version of Swift, might be something related to CocoaPods. It was upgraded on September last year.

https://github.com/3lvis/Hex/releases/tag/4.0.0
